import { test } from "@playwright/test";
import { LoginPage } from "./pages/login-page.jsx";
import { PersonAccPage } from "./pages/person-acc-page.jsx";
import { UsersPage } from "./pages/user-page.jsx";
import users from '../__fixtures__/users.jsx'

test('application display', async ({ page }) => {
  const loginPage = new LoginPage(page)
  await loginPage.navigateToLoginPage()
  expect(`input[name="username"]`).toBeVisible()
  expect(`input[name="password"]`).toBeVisible()
  expect(`text="Sign in"`).toBeVisible()
})

test("login", async ({ page }) => {
  const loginPage = new LoginPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  expect(`text="Lorem ipsum sic dolor amet..."`).toBeVisible()
})

test("negative - login", async ({ page }) => {
  const loginPage = new LoginPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('', '')
  expect(`text="The form is not valid. Please check for errors"`).toBeVisible()
  await loginPage.loginWithoutUsername('Password')
  expect(`text="The form is not valid. Please check for errors"`).toBeVisible()
  await loginPage.loginWithoutPassword('Username')
  expect(`text="The form is not valid. Please check for errors"`).toBeVisible()
})

test("logout", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const personAccPage = new PersonAccPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  expect(`text="Lorem ipsum sic dolor amet..."`).toBeVisible()
  await personAccPage.logOut()
  expect(`input[name="username"]`).toBeVisible()
  expect(`input[name="password"]`).toBeVisible()
  expect(`text="Sign in"`).toBeVisible()
})

test("create user", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.createUser('email@gmail.com', 'FirstName', 'LastName')
  expect(`text="Element created"`).toBeVisible()
  expect(`text="email@gmail.com"`).toBeVisible() 
  expect(`text="FirstName"`).toBeVisible()
  expect(`text="LastName"`).toBeVisible()
  expect(`[aria-label="Show"]`).toBeVisible()
  expect(`[disabled][aria-label="Save"]`).toBeVisible()
  expect(`[aria-label="Delete"]`).toBeVisible()
  await usersPage.clickShowButton()
  expect(`text="email@gmail.com"`).toBeVisible()
  expect(`text="FirstName"`).toBeVisible()
  expect(`text="LastName"`).toBeVisible()
  expect(`[aria-label="Edit"]`).toBeVisible()
  await usersPage.navigateToUsersPage()  
  expect(`text="email@gmail.com"`).toBeVisible()
  expect(`text="FirstName"`).toBeVisible()
  expect(`text="LastName"`).toBeVisible() 
})

test("user list", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login()
  await usersPage.navigateToUsersPage()
  for(const user of users)
  {
    expect(`text="${user.Email}"`).toBeVisible()
    expect(`text="${user.FirstName}"`).toBeVisible()
    expect(`text="${user.LastName}"`).toBeVisible()
  }
})

test("editing form", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.openUserData('john@google.com')
  expect(`text="${users[0].Email}"`).toBeVisible()
  expect(`text="${users[0].FirstName}"`).toBeVisible()
  expect(`text="${users[0].LastName}"`).toBeVisible()
  expect(`[aria-label="Show"]`).toBeVisible()
  expect(`[disabled][aria-labels="Save"]`).toBeVisible()
  expect(`[aria-label="Delete"]`).toBeVisible()
})

test("edit user", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.editUser('john@google.com', 'ChangedFirstName')
  await usersPage.navigateToUsersPage()
  expect(`text="${users[0].Email}"`).toBeVisible()
  expect(`text="ChangedFirstName"`).toBeVisible()
  expect(`text="${users[0].LastName}"`).toBeVisible()
  expect(`text="${users[0].FirstName}"`).not.toBeVisible()  
})

test("edit user from create form", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.createUser('useremail@gmail.com', 'UserFirstName', 'UserLastName')
  await usersPage.clickShowButton()
  await usersPage.editUserClickingEditButton('ChangedFirstName')
  await usersPage.navigateToUsersPage()
  expect(`text="useremail@gmail.com"`).toBeVisible()
  expect(`text="ChangedFirstName"`).toBeVisible()
  expect(`text="UserLastName"`).toBeVisible()
  expect(`text="UserFirstName"`).not.toBeVisible() 
})

test("negative - edit user", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.editUser('john@google.com', '')
  expect(`text="The form is not valid. Please check for errors"`).toBeVisible()
})

test("delete user", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.deleteUser('john@google.com')
  await usersPage.navigateToUsersPage()
  expect(`text="${users[0].Email}"`).not.toBeVisible()
  expect(`text="${users[0].FirstName}"`).not.toBeVisible()
  expect(`text="${users[0].LastName}"`).not.toBeVisible()
})

test("delete all user", async ({ page }) => {
  const loginPage = new LoginPage(page)
  const usersPage = new UsersPage(page)
  await loginPage.navigateToLoginPage()
  await loginPage.login('Username', 'Password')
  await usersPage.navigateToUsersPage()
  await usersPage.deleteAllUsers()
  await usersPage.navigateToUsersPage()
  expect(`text="No Users yet."`).toBeVisible()
})
