const textVault = {
  username: "testusername",
  password: "u3dxl4Sh",
  errorTextLoginPage: "The form is not valid. Please check for errors",
  welcomeText: "Welcome to the administration",
  additionalWelcomeText: "Lorem ipsum sic dolor amet...",
  createUserEmail: "test@mail.ru",
  userEmail: "email@gmail.com",
  userFirstName: "Test",
  userLastName: "Ongoing",
  firstUserEmail: "john@google.com",
  changedUserFirstName: "ChangedFirstName",
  noUsersText: "No Users yet.",
  userPageElementCreatedMessage: "Element created",
  createUserDeleteButton: "Delete",
  createUserShow: "Show",
  createUserEditButton: "Edit",
  statusName: "TestName",
  statusSlug: "TestSlug",
  changedStatusName: "ChangedName",
  changedStatusSlug: "ChangedSlug",
  noStatusText: "No Task statuses yet.",
  labelName: "TestLabel",
  changedLabelName: "TestLabelEdit",
  noLabelsText: "No Labels yet.",
  labelsForDeletionNum1: "1",
  labelsForDeletionName1: "bug",
  labelsForDeletionNum2: "2",
  labelsForDeletionName2: "feature",
  labelsForDeletionNum3: "3",
  labelsForDeletionName3: "enhancement",
  taskAssigneeEmail: "john@google.com",
  taskTitle: "Title",
  taskStatusOption: "To Review",
  taskTitleChanged: "ChangedTitle",
  task1Title: "Task 1",
  task2Title: "Task 2",
  task3Title: "Task 3",
  task4Title: "Task 4",
  task5Title: "Task 5",
  task6Title: "Task 6",
  task7Title: "Task 7",
  task8Title: "Task 8",
  task9Title: "Task 9",
  task10Title: "Task 10",
  task11Title: "Task 11",
  task12Title: "Task 12",
  task13Title: "Task 13",
  task14Title: "Task 14",
  task15Title: "Task 15",
  assigneeFilterOption: "john@google.com",
  statusFilterOption: "Published",
  labelFilterOption: "critical",
};

export default textVault;
