const textVault = {
  username: "testusername",
  password: "u3dxl4Sh",
  errorTextLoginPage: "The form is not valid. Please check for errors",
  welcomeText: "Welcome to the administration",
  additionalWelcomeText: "Lorem ipsum sic dolor amet...",
  userEmail: "email@gmail.com",
  userFirstName: "Test",
  userLastName: "Ongoing",
  firstUserEmail: "john@google.com",
  changedUserFirstName: "ChangedFirstName",
  noUsersText: "No Users yet.",
  userPageElementCreatedMessage: "Element created",
  statusName: "TestName",
  statusSlug: "TestSlug",
  changedStatusName: "ChangedName",
  changedStatusSlug: "ChangedSlug",
  noStatusText: "No Task statuses yet.",
  labelName: "TestLabel",
  changedLabelName: "TestLabelEdit",
  noLabelsText: "No Labels yet.",
  labelsForDeletionNum1: "1",
  labelsForDeletionName1: "bug",
  labelsForDeletionNum2: "2",
  labelsForDeletionName2: "feature",
  labelsForDeletionNum3: "3",
  labelsForDeletionName3: "enhancement",
  taskAssigneeEmail: "john@google.com",
  taskTitle: "Title",
  taskStatusOption: "To Review",
  taskTitleChanged: "ChangedTitle",
  taskTitle1: "Task 1",
  taskTitle2: "Task 2",
  taskTitle3: "Task 3",
  taskTitle4: "Task 4",
  taskTitle5: "Task 5",
  taskTitle6: "Task 6",
  taskTitle7: "Task 7",
  taskTitle8: "Task 8",
  taskTitle9: "Task 9",
  taskTitle10: "Task 10",
  taskTitle11: "Task 11",
  taskTitle12: "Task 12",
  taskTitle13: "Task 13",
  taskTitle14: "Task 14",
  taskTitle15: "Task 15",
  assigneeFilterOption: "john@google.com",
  statusFilterOption: "Published",
  labelFilterOption: "critical",
};

export default textVault;
